export let countries = [
	{ value: 'us', label: 'United States' },
	{ value: 'fr', label: 'France' },
	{ value: 'gb', label: 'United Kingdom' },
	{ value: 'de', label: 'Germany' },
	{ value: 'jp', label: 'Japan' },
	{ value: 'au', label: 'Australia' },
	{ value: 'cn', label: 'China' },
	{ value: 'in', label: 'India' },
	{ value: 'mx', label: 'Mexico' },
	{ value: 'br', label: 'Brazil' },
	{ value: 'ru', label: 'Russia' },
	{ value: 'it', label: 'Italy' },
	{ value: 'es', label: 'Spain' },
	{ value: 'id', label: 'Indonesia' },
	{ value: 'tr', label: 'Turkey' },
	{ value: 'kr', label: 'South Korea' },
	{ value: 'ca', label: 'Canada' },
	{ value: 'sa', label: 'Saudi Arabia' },
	{ value: 'ar', label: 'Argentina' },
	{ value: 'za', label: 'South Africa' },
	{ value: 'ir', label: 'Iran' },
	{ value: 'nl', label: 'Netherlands' },
	{ value: 'ch', label: 'Switzerland' },
	{ value: 'sg', label: 'Singapore' },
	{ value: 'eg', label: 'Egypt' },
	{ value: 'vn', label: 'Vietnam' },
	{ value: 'th', label: 'Thailand' },
	{ value: 'pl', label: 'Poland' },
	{ value: 'se', label: 'Sweden' }
];
